name: jellyseerr
services:
  jellyseerr:
    image: ghcr.io/hotio/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    restart: unless-stopped
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
      UMASK: "002"
    volumes:
      - /DATA/AppData/jellyseerr/config:/config
    ports:
      - "5055:5055"
    networks:
      - jellyfin_default
      - hotio_default
    deploy:
      resources:
        limits:
          memory: "67289219072"

networks:
  jellyfin_default:
    external: true
    name: jellyfin_default
  hotio_default:
    external: true
    name: hotio_default
