name: hotio
services:
  qbittorrent:
    image: cr.hotio.dev/hotio/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    cpu_shares: 50
    deploy:
      resources:
        limits:
          memory: "18480103424"
    dns:
      - 10.64.0.1
      - 1.1.1.1
      - 1.0.0.1
    environment:
      PGID: "1000"
      PRIVOXY_ENABLED: "true"
      PUID: "1000"
      TZ: Etc/UTC
      UMASK: "002"
      VPN_ADDITIONAL_PORTS: 6789/tcp,6789/udp
      VPN_CONF: wg0
      VPN_ENABLED: "true"
      VPN_IP_CHECK_DELAY: "10"
      VPN_IP_CHECK_EXIT: "true"
      VPN_LAN_NETWOK: 192.168.0.0/24
      WEBUI_PORTS: 8080/tcp,8080/udp
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
      - mode: ingress
        target: 8118
        published: "8118"
        protocol: tcp
      - mode: ingress
        target: 6789
        published: "6789"
        protocol: tcp
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv6.conf.all.disable_ipv6: "1"
    volumes:
      - type: bind
        source: /hive/Hotio/config
        target: /config
        bind:
          create_host_path: true
      - type: bind
        source: /hive/downloads/completed
        target: /downloads
        bind:
          create_host_path: true
    logging:
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: hotio_default
