services:
  cosmos-server:
    image: azukaar/cosmos-server:latest
    container_name: cosmos-server
    hostname: cosmos-server
    restart: unless-stopped
    privileged: true
    ports:
      - "89:80"
      - "9443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /:/mnt/host
      - /var/lib/cosmos:/config
    logging:
      options:
        max-size: "10m"
        max-file: "3"
