name: jellyfin
services:
  jellyfin:
    container_name: jellyfin
    deploy:
      resources:
        limits:
          memory: "4294967296"
    devices:
      - source: /dev/dri
        target: /dev/dri
        permissions: rwm
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
      UMASK: "002"
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsS http://127.0.0.1:8096/health >/dev/null || exit 1
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 1m0s
    image: ghcr.io/hotio/jellyfin:release-10.11.6
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.fatherfankscloud.uk`)
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.tls.certresolver: le
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
    logging:
      options:
        max-file: "3"
        max-size: 10m
    networks:
      proxy: null
    ports:
      - mode: ingress
        target: 8096
        published: "8096"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /mnt/monarch/appdata/jellyfin
        target: /config
        bind: {}
      - type: bind
        source: /hive/jellyfin/tv
        target: /data/tvshows
        bind: {}
      - type: bind
        source: /hive/jellyfin/movie
        target: /data/movies
        bind: {}
networks:
  proxy:
    name: proxy
    external: true
