name: prowlarr
services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Etc/UTC
      UMASK: "002"
    volumes:
      - /DATA/AppData/config:/config
    ports:
      - "9696:9696"
    networks:
      - hotio_default
    deploy:
      resources:
        limits:
          memory: "12111052800"

networks:
  hotio_default:
    external: true
    name: hotio_default
