services:
  logseq:
    image: ghcr.io/logseq/logseq-webapp:latest
    container_name: logseq-web
    restart: unless-stopped
    ports:
      - "3001:80"
    volumes:
      - /hive/echoos:/graph
    environment:
      LOGSEQ_GRAPH: /graph
    networks:
      - echoos_net
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1g

networks:
  echoos_net:
    name: echoos_net
