services:
  logseq:
    image: ghcr.io/logseq/logseq-webapp:latest
    container_name: logseq-web
    restart: unless-stopped

    volumes:
      - /hive/echoos:/graph

    environment:
      LOGSEQ_GRAPH: /graph

    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.logseq.rule=Host(`echo.fatherfankscloud.uk`)"
      - "traefik.http.routers.logseq.entrypoints=websecure"
      - "traefik.http.routers.logseq.tls=true"
      - "traefik.http.routers.logseq.tls.certresolver=letsencrypt"

      # Service
      - "traefik.http.services.logseq.loadbalancer.server.port=80"

    networks:
      - proxy
      - ai_net
networks:
  proxy:
    external: true
  ai_net:
    external: true